package com.aryaa.sdm.service;
import com.aryaa.sdm.dto.*; import com.aryaa.sdm.exception.*; import com.aryaa.sdm.model.*; import com.aryaa.sdm.repository.*; import com.aryaa.sdm.util.GeoUtils; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @Transactional
public class AdmissionService {
 private final PatientRepository patients; private final RegionService regions; private final HospitalRepository hospitals; private final EventBroadcastService events;
 public AdmissionService(PatientRepository p,RegionService r,HospitalRepository h,EventBroadcastService e){patients=p;regions=r;hospitals=h;events=e;}
 public AdmissionResult admitWaitingPatients(String name){Region disaster=regions.getRegionOrThrow(name);PriorityQueue<Patient> q=new PriorityQueue<>(Comparator.comparing(Patient::getSeverity).reversed());q.addAll(patients.findByStatus(PatientStatus.WAITING));List<PatientDto> admitted=new ArrayList<>(),unassigned=new ArrayList<>();while(!q.isEmpty()){Patient p=q.poll();Optional<AssignedBed> bed=findBed(disaster);if(bed.isPresent()){var b=bed.get();p.admitTo(b.hospital(),b.region());admitted.add(PatientDto.from(p,b.distance()));}else{p.setStatus(PatientStatus.UNASSIGNED);unassigned.add(PatientDto.from(p));}}AdmissionResult out=new AdmissionResult(disaster.getName(),admitted,unassigned);events.broadcast("admission",out);return out;}
 public PatientDto dischargePatient(Long id){Patient p=patients.findById(id).orElseThrow(()->new ResourceNotFoundException("Unknown patient id: "+id));if(p.getStatus()!=PatientStatus.ADMITTED)throw new InvalidOperationException("Patient "+id+" is not currently admitted");if(p.getAssignedHospital()!=null)hospitals.tryReleaseBed(p.getAssignedHospital().getId());p.discharge();PatientDto out=PatientDto.from(p);events.broadcast("discharge",out);return out;}
 private Optional<AssignedBed> findBed(Region disaster){Optional<AssignedBed> local=claim(disaster.getName(),disaster.getName(),0);if(local.isPresent())return local;return regions.getAllRegionEntities().stream().filter(r->!r.getName().equalsIgnoreCase(disaster.getName())&&!r.isDisasterActive()).sorted(Comparator.comparingDouble(r->GeoUtils.haversineKm(disaster.getLatitude(),disaster.getLongitude(),r.getLatitude(),r.getLongitude()))).map(r->claim(r.getName(),r.getName(),GeoUtils.haversineKm(disaster.getLatitude(),disaster.getLongitude(),r.getLatitude(),r.getLongitude()))).filter(Optional::isPresent).map(Optional::get).findFirst();}
 private Optional<AssignedBed> claim(String region,String label,double distance){for(Hospital h:regions.getHospitals(region)){if(hospitals.tryOccupyBed(h.getId())==1)return Optional.of(new AssignedBed(h,label,distance));}return Optional.empty();}
 private record AssignedBed(Hospital hospital,String region,double distance){}
}